-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  first_name text,
  last_name text,
  middle_name text,
  phone text,
  role text NOT NULL DEFAULT 'student'::text CHECK (role = ANY (ARRAY['student'::text, 'lecturer'::text, 'admin'::text, 'super_admin'::text, 'aspirant'::text])),
  avatar_url text,
  is_active boolean NOT NULL DEFAULT true,
  last_seen_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  profile_photo_bucket text NOT NULL DEFAULT 'profile-photos'::text,
  profile_photo_path text UNIQUE,
  profile_photo_mime_type text,
  profile_photo_uploaded_by uuid,
  profile_photo_uploaded_at timestamp with time zone,
  media_provider text NOT NULL DEFAULT 'cloudinary'::text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_profile_photo_uploaded_by_fkey FOREIGN KEY (profile_photo_uploaded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.student_profiles (
  profile_id uuid NOT NULL,
  student_number text UNIQUE,
  matric_number text UNIQUE,
  admission_session text,
  admission_date date,
  date_of_birth date,
  gender text CHECK (gender = ANY (ARRAY['male'::text, 'female'::text, 'other'::text, 'prefer_not_to_say'::text])),
  blood_group text,
  genotype text,
  state_of_origin text,
  local_government_area text,
  nationality text DEFAULT 'Nigerian'::text,
  address_line_1 text,
  address_line_2 text,
  city text,
  state text,
  guardian_name text,
  guardian_phone text,
  guardian_email text,
  emergency_contact_name text,
  emergency_contact_phone text,
  current_level text,
  admission_status text DEFAULT 'active'::text CHECK (admission_status = ANY (ARRAY['active'::text, 'suspended'::text, 'graduated'::text, 'withdrawn'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT student_profiles_pkey PRIMARY KEY (profile_id),
  CONSTRAINT student_profiles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.admin_profiles (
  profile_id uuid NOT NULL,
  staff_id text UNIQUE,
  department USER-DEFINED,
  designation USER-DEFINED,
  admin_scope text DEFAULT 'operations'::text CHECK (admin_scope = ANY (ARRAY['operations'::text, 'academics'::text, 'finance'::text, 'super'::text])),
  can_manage_users boolean NOT NULL DEFAULT false,
  can_manage_content boolean NOT NULL DEFAULT false,
  can_manage_academics boolean NOT NULL DEFAULT false,
  can_manage_finance boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_profiles_pkey PRIMARY KEY (profile_id),
  CONSTRAINT admin_profiles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.academic_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  starts_on date,
  ends_on date,
  is_current boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT academic_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.departments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  code text UNIQUE,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT departments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.programs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  description text NOT NULL,
  overview text,
  entry_requirements text,
  career_prospects text,
  duration_months integer NOT NULL,
  duration_unit text NOT NULL CHECK (duration_unit = ANY (ARRAY['months'::text, 'years'::text])),
  tuition_fee numeric,
  curriculum text,
  level text NOT NULL CHECK (level = ANY (ARRAY['certificate'::text, 'diploma'::text, 'degree'::text])),
  department_id uuid,
  max_students integer,
  admission_open boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT programs_pkey PRIMARY KEY (id),
  CONSTRAINT programs_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.courses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  program_id uuid,
  code text NOT NULL UNIQUE,
  title text NOT NULL,
  description text,
  credit_units integer DEFAULT 1,
  level text,
  semester integer,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT courses_pkey PRIMARY KEY (id),
  CONSTRAINT courses_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id)
);
CREATE TABLE public.course_teacher_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  course_id uuid NOT NULL,
  teacher_id uuid NOT NULL,
  session_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  semester_id uuid,
  CONSTRAINT course_teacher_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT course_teacher_assignments_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT course_teacher_assignments_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.academic_sessions(id),
  CONSTRAINT course_teacher_assignments_semester_id_fkey FOREIGN KEY (semester_id) REFERENCES public.academic_semesters(id)
);
CREATE TABLE public.enrollments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  program_id uuid NOT NULL,
  session_id uuid,
  enrollment_date timestamp with time zone NOT NULL DEFAULT now(),
  expected_graduation_date date,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'dropped'::text, 'deferred'::text, 'withdrawn'::text])),
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT enrollments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT enrollments_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id),
  CONSTRAINT enrollments_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.academic_sessions(id)
);
CREATE TABLE public.assessments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  enrollment_id uuid NOT NULL,
  student_id uuid NOT NULL,
  course_id uuid,
  teacher_id uuid,
  session_id uuid,
  exam_score numeric DEFAULT 0 CHECK (exam_score >= 0::numeric AND exam_score <= 60::numeric),
  grade text CHECK (grade = ANY (ARRAY['A'::text, 'B'::text, 'C'::text, 'D'::text, 'E'::text, 'F'::text])),
  score_status text NOT NULL DEFAULT 'draft'::text CHECK (score_status = ANY (ARRAY['draft'::text, 'submitted'::text, 'approved'::text, 'published'::text])),
  score_entered_at timestamp with time zone,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  semester_id uuid,
  ca_1 numeric DEFAULT 0 CHECK (ca_1 >= 0::numeric AND ca_1 <= 15::numeric),
  ca_2 numeric DEFAULT 0 CHECK (ca_2 >= 0::numeric AND ca_2 <= 15::numeric),
  assignments numeric DEFAULT 0 CHECK (assignments >= 0::numeric AND assignments <= 10::numeric),
  continuous_assessment numeric DEFAULT ((COALESCE(ca_1, (0)::numeric) + COALESCE(ca_2, (0)::numeric)) + COALESCE(assignments, (0)::numeric)),
  total_score numeric DEFAULT (((COALESCE(ca_1, (0)::numeric) + COALESCE(ca_2, (0)::numeric)) + COALESCE(assignments, (0)::numeric)) + COALESCE(exam_score, (0)::numeric)),
  CONSTRAINT assessments_pkey PRIMARY KEY (id),
  CONSTRAINT assessments_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(id),
  CONSTRAINT assessments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT assessments_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT assessments_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.academic_sessions(id),
  CONSTRAINT assessments_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.admin_profiles(profile_id),
  CONSTRAINT assessments_semester_id_fkey FOREIGN KEY (semester_id) REFERENCES public.academic_semesters(id)
);
CREATE TABLE public.results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  enrollment_id uuid NOT NULL,
  assessment_id uuid,
  course_name text NOT NULL,
  score numeric CHECK (score >= 0::numeric AND score <= 100::numeric),
  grade text CHECK (grade = ANY (ARRAY['A'::text, 'B'::text, 'C'::text, 'D'::text, 'E'::text, 'F'::text])),
  semester integer,
  academic_year text,
  published boolean NOT NULL DEFAULT false,
  published_at timestamp with time zone,
  published_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT results_pkey PRIMARY KEY (id),
  CONSTRAINT results_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT results_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(id),
  CONSTRAINT results_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id),
  CONSTRAINT results_published_by_fkey FOREIGN KEY (published_by) REFERENCES public.admin_profiles(profile_id)
);
CREATE TABLE public.result_publications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  enrollment_id uuid NOT NULL,
  session_id uuid,
  published_by uuid,
  publication_status text NOT NULL DEFAULT 'published'::text CHECK (publication_status = ANY (ARRAY['published'::text, 'unpublished'::text])),
  published_at timestamp with time zone NOT NULL DEFAULT now(),
  notes text,
  semester_id uuid,
  CONSTRAINT result_publications_pkey PRIMARY KEY (id),
  CONSTRAINT result_publications_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(id),
  CONSTRAINT result_publications_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.academic_sessions(id),
  CONSTRAINT result_publications_published_by_fkey FOREIGN KEY (published_by) REFERENCES public.admin_profiles(profile_id),
  CONSTRAINT result_publications_semester_id_fkey FOREIGN KEY (semester_id) REFERENCES public.academic_semesters(id)
);
CREATE TABLE public.blog_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  content text NOT NULL,
  excerpt text,
  author_id uuid,
  featured_image_url text,
  tags ARRAY DEFAULT '{}'::text[],
  seo_title text,
  seo_description text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'review'::text, 'published'::text, 'archived'::text])),
  published_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT blog_posts_pkey PRIMARY KEY (id),
  CONSTRAINT blog_posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text NOT NULL,
  event_date timestamp with time zone NOT NULL,
  event_end_date timestamp with time zone,
  location text,
  organizer_id uuid,
  featured_image_url text,
  registration_link text,
  is_published boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_organizer_id_fkey FOREIGN KEY (organizer_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.notices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  content text NOT NULL,
  audience text NOT NULL DEFAULT 'all'::text CHECK (audience = ANY (ARRAY['all'::text, 'students'::text, 'teachers'::text, 'admins'::text])),
  created_by uuid,
  is_published boolean NOT NULL DEFAULT false,
  published_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notices_pkey PRIMARY KEY (id),
  CONSTRAINT notices_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.announcements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  content text NOT NULL,
  created_by uuid,
  is_published boolean NOT NULL DEFAULT false,
  published_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT announcements_pkey PRIMARY KEY (id),
  CONSTRAINT announcements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.contact_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  email text NOT NULL,
  subject text NOT NULL,
  message text NOT NULL,
  status text NOT NULL DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'in_progress'::text, 'resolved'::text, 'archived'::text])),
  handled_by uuid,
  handled_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT contact_messages_pkey PRIMARY KEY (id),
  CONSTRAINT contact_messages_handled_by_fkey FOREIGN KEY (handled_by) REFERENCES public.admin_profiles(profile_id)
);
CREATE TABLE public.fees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  program_id uuid NOT NULL,
  fee_type text NOT NULL CHECK (fee_type = ANY (ARRAY['tuition'::text, 'registration'::text, 'exam'::text, 'library'::text, 'other'::text])),
  amount numeric NOT NULL,
  description text,
  due_in_days integer,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fees_pkey PRIMARY KEY (id),
  CONSTRAINT fees_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  enrollment_id uuid,
  session_id uuid,
  invoice_number text UNIQUE,
  description text,
  amount_due numeric NOT NULL,
  amount_paid numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'NGN'::text,
  due_date date,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'partially_paid'::text, 'paid'::text, 'failed'::text, 'cancelled'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  semester_id uuid,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.academic_sessions(id),
  CONSTRAINT invoices_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT invoices_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(id),
  CONSTRAINT invoices_semester_id_fkey FOREIGN KEY (semester_id) REFERENCES public.academic_semesters(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  enrollment_id uuid,
  invoice_id uuid,
  amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'NGN'::text,
  payment_method text CHECK (payment_method = ANY (ARRAY['paystack'::text, 'bank_transfer'::text, 'cash'::text])),
  paystack_reference text UNIQUE,
  paystack_access_code text,
  provider_transaction_id text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text, 'abandoned'::text, 'refunded'::text])),
  description text,
  paid_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT payments_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(id),
  CONSTRAINT payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.payment_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_id uuid,
  invoice_id uuid,
  event_type text NOT NULL,
  provider text DEFAULT 'paystack'::text,
  provider_reference text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  signature text,
  processed boolean NOT NULL DEFAULT false,
  processed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_events_pkey PRIMARY KEY (id),
  CONSTRAINT payment_events_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id),
  CONSTRAINT payment_events_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.student_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  notification_type text NOT NULL DEFAULT 'general'::text,
  category text,
  deep_link text,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  sent_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT student_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT student_notifications_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.student_profiles(profile_id),
  CONSTRAINT student_notifications_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.admin_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  notification_type text NOT NULL DEFAULT 'general'::text,
  category text,
  deep_link text,
  priority text NOT NULL DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'critical'::text])),
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  sent_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT admin_notifications_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.admin_profiles(profile_id),
  CONSTRAINT admin_notifications_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.school_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  value text,
  value_json jsonb,
  is_public boolean NOT NULL DEFAULT false,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT school_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_id uuid,
  actor_role text,
  action text NOT NULL,
  entity_name text NOT NULL,
  entity_id uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.aspirant_profiles (
  profile_id uuid NOT NULL,
  admission_number text UNIQUE,
  jamb_reg_no text UNIQUE,
  preferred_program_id uuid,
  application_type text NOT NULL DEFAULT 'Fresh admission'::text CHECK (application_type = ANY (ARRAY['Fresh admission'::text, 'Transfer candidate'::text, 'Returning applicant'::text, 'Special consideration'::text])),
  application_status text NOT NULL DEFAULT 'draft'::text CHECK (application_status = ANY (ARRAY['draft'::text, 'incomplete'::text, 'submitted'::text, 'under_review'::text, 'correction_required'::text, 'approved'::text, 'rejected'::text])),
  current_stage text NOT NULL DEFAULT 'signup'::text CHECK (current_stage = ANY (ARRAY['signup'::text, 'payment'::text, 'documents'::text, 'exam'::text, 'admission_fee'::text, 'migration'::text, 'completed'::text])),
  profile_completion integer NOT NULL DEFAULT 0 CHECK (profile_completion >= 0 AND profile_completion <= 100),
  admission_session text,
  submission_notes text,
  submitted_at timestamp with time zone,
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  review_feedback text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  application_fee_paid boolean NOT NULL DEFAULT false,
  application_fee_paid_at timestamp with time zone,
  admission_fee_paid boolean NOT NULL DEFAULT false,
  admission_fee_paid_at timestamp with time zone,
  documents_uploaded boolean NOT NULL DEFAULT false,
  documents_uploaded_at timestamp with time zone,
  exam_completed boolean NOT NULL DEFAULT false,
  exam_completed_at timestamp with time zone,
  exam_score numeric,
  exam_grade text,
  migration_completed boolean NOT NULL DEFAULT false,
  migration_completed_at timestamp with time zone,
  matric_number text,
  CONSTRAINT aspirant_profiles_pkey PRIMARY KEY (profile_id),
  CONSTRAINT aspirant_profiles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT aspirant_profiles_preferred_program_id_fkey FOREIGN KEY (preferred_program_id) REFERENCES public.programs(id),
  CONSTRAINT aspirant_profiles_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.admin_profiles(profile_id)
);
CREATE TABLE public.admission_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL,
  uploaded_by uuid NOT NULL,
  document_type text NOT NULL CHECK (document_type = ANY (ARRAY['passport_photo'::text, 'signature'::text, 'birth_certificate'::text, 'medical_fitness'::text, 'age_declaration'::text, 'primary_certificate'::text, 'secondary_certificate'::text, 'indigene_certificate'::text, 'nin_slip'::text, 'jamb_result'::text, 'jamb_registration_form'::text, 'other'::text])),
  storage_bucket text NOT NULL DEFAULT 'admission-documents'::text,
  storage_path text NOT NULL UNIQUE,
  file_name text NOT NULL,
  mime_type text,
  file_size bigint,
  verification_status text NOT NULL DEFAULT 'pending'::text CHECK (verification_status = ANY (ARRAY['pending'::text, 'verified'::text, 'rejected'::text, 'needs_correction'::text])),
  verification_note text,
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  verified_by uuid,
  verified_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  media_provider text NOT NULL DEFAULT 'cloudinary'::text,
  CONSTRAINT admission_documents_pkey PRIMARY KEY (id),
  CONSTRAINT admission_documents_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.aspirant_profiles(profile_id),
  CONSTRAINT admission_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id),
  CONSTRAINT admission_documents_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.admin_profiles(profile_id)
);
CREATE TABLE public.aspirant_profile_photos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL,
  uploaded_by uuid NOT NULL,
  storage_bucket text NOT NULL DEFAULT 'profile-photos'::text,
  storage_path text NOT NULL UNIQUE,
  file_name text NOT NULL,
  mime_type text,
  file_size bigint,
  is_primary boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  media_provider text NOT NULL DEFAULT 'cloudinary'::text,
  CONSTRAINT aspirant_profile_photos_pkey PRIMARY KEY (id),
  CONSTRAINT aspirant_profile_photos_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.aspirant_profiles(profile_id),
  CONSTRAINT aspirant_profile_photos_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.admission_status_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL,
  previous_status text,
  new_status text NOT NULL,
  note text,
  changed_by uuid,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admission_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT admission_status_history_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.aspirant_profiles(profile_id),
  CONSTRAINT admission_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.aspirant_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  aspirant_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  notification_type text NOT NULL DEFAULT 'general'::text,
  category text NOT NULL DEFAULT 'general'::text,
  deep_link text,
  is_read boolean NOT NULL DEFAULT false,
  priority text NOT NULL DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT aspirant_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT aspirant_notifications_aspirant_id_fkey FOREIGN KEY (aspirant_id) REFERENCES public.profiles(id),
  CONSTRAINT aspirant_notifications_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.aspirant_academic_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  aspirant_id uuid NOT NULL,
  result_type text NOT NULL DEFAULT 'secondary'::text CHECK (result_type = ANY (ARRAY['secondary'::text, 'diploma'::text, 'nce'::text, 'hnd'::text, 'degree'::text, 'professional'::text])),
  exam_body text NOT NULL CHECK (exam_body = ANY (ARRAY['WAEC'::text, 'NECO'::text, 'NABTEB'::text, 'IJMB'::text, 'JUPEB'::text, 'Diploma'::text, 'Other'::text])),
  exam_year integer,
  sitting_number integer NOT NULL DEFAULT 1 CHECK (sitting_number = ANY (ARRAY[1, 2])),
  is_combined boolean NOT NULL DEFAULT false,
  qualification_title text,
  institution_name text,
  result_summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  file_bucket text DEFAULT 'admission-documents'::text,
  file_path text,
  file_name text,
  file_mime_type text,
  verification_status text NOT NULL DEFAULT 'pending'::text CHECK (verification_status = ANY (ARRAY['pending'::text, 'verified'::text, 'rejected'::text, 'needs_correction'::text])),
  verification_note text,
  verified_by uuid,
  verified_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT aspirant_academic_results_pkey PRIMARY KEY (id),
  CONSTRAINT aspirant_academic_results_aspirant_id_fkey FOREIGN KEY (aspirant_id) REFERENCES public.profiles(id),
  CONSTRAINT aspirant_academic_results_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.admin_profiles(profile_id),
  CONSTRAINT aspirant_academic_results_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.academic_semesters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  semester_name text NOT NULL CHECK (semester_name = ANY (ARRAY['First Semester'::text, 'Second Semester'::text])),
  starts_on date,
  ends_on date,
  is_current boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT academic_semesters_pkey PRIMARY KEY (id),
  CONSTRAINT academic_semesters_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.academic_sessions(id)
);
CREATE TABLE public.teacher_profiles (
  profile_id uuid NOT NULL,
  employee_number text UNIQUE,
  staff_number text UNIQUE,
  qualification text,
  specialization text,
  department text,
  employment_type text CHECK (employment_type = ANY (ARRAY['full_time'::text, 'part_time'::text, 'adjunct'::text, 'contract'::text])),
  date_joined date,
  office_location text,
  office_hours text,
  can_publish_results boolean NOT NULL DEFAULT false,
  can_enter_scores boolean NOT NULL DEFAULT true,
  employment_status text DEFAULT 'active'::text CHECK (employment_status = ANY (ARRAY['active'::text, 'inactive'::text, 'suspended'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT teacher_profiles_pkey PRIMARY KEY (profile_id),
  CONSTRAINT teacher_profiles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.teacher_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  notification_type text NOT NULL DEFAULT 'general'::text,
  category text,
  deep_link text,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  sent_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT teacher_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT teacher_notifications_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teacher_profiles(profile_id),
  CONSTRAINT teacher_notifications_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.proctoring_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  aspirant_id uuid NOT NULL,
  event_type text NOT NULL,
  violation_details text,
  screenshot_url text,
  device_fingerprint text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT proctoring_logs_pkey PRIMARY KEY (id),
  CONSTRAINT proctoring_logs_aspirant_id_fkey FOREIGN KEY (aspirant_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.entrance_exam_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  aspirant_id uuid NOT NULL,
  exam_type text NOT NULL DEFAULT 'entrance'::text,
  score numeric NOT NULL CHECK (score >= 0::numeric AND score <= 100::numeric),
  total_questions integer NOT NULL CHECK (total_questions > 0),
  percentage numeric NOT NULL CHECK (percentage >= 0::numeric AND percentage <= 100::numeric),
  grade text NOT NULL CHECK (grade = ANY (ARRAY['A'::text, 'B'::text, 'C'::text, 'D'::text, 'E'::text, 'F'::text])),
  answers jsonb NOT NULL DEFAULT '{}'::jsonb,
  proctoring_snapshot jsonb,
  status text NOT NULL DEFAULT 'submitted'::text CHECK (status = ANY (ARRAY['submitted'::text, 'reviewed'::text, 'approved'::text, 'rejected'::text])),
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  review_note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT entrance_exam_results_pkey PRIMARY KEY (id),
  CONSTRAINT entrance_exam_results_aspirant_id_fkey FOREIGN KEY (aspirant_id) REFERENCES public.profiles(id),
  CONSTRAINT entrance_exam_results_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.admin_profiles(profile_id)
);
CREATE TABLE public.entrance_exam_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  exam_name text NOT NULL DEFAULT 'Entrance Examination'::text,
  exam_description text,
  duration_minutes integer NOT NULL DEFAULT 10,
  total_questions integer NOT NULL DEFAULT 4,
  passing_score numeric NOT NULL DEFAULT 50,
  is_active boolean NOT NULL DEFAULT true,
  instructions text,
  created_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT entrance_exam_config_pkey PRIMARY KEY (id),
  CONSTRAINT entrance_exam_config_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.exam_questions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  exam_config_id uuid NOT NULL,
  question_text text NOT NULL,
  question_type text NOT NULL DEFAULT 'multiple_choice'::text CHECK (question_type = ANY (ARRAY['multiple_choice'::text, 'true_false'::text, 'essay'::text])),
  options jsonb NOT NULL DEFAULT '[]'::jsonb,
  correct_answer text NOT NULL,
  points numeric NOT NULL DEFAULT 1,
  question_order integer NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT exam_questions_pkey PRIMARY KEY (id),
  CONSTRAINT exam_questions_exam_config_id_fkey FOREIGN KEY (exam_config_id) REFERENCES public.entrance_exam_config(id)
);
CREATE TABLE public.exam_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  aspirant_id uuid NOT NULL,
  exam_config_id uuid,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  submitted_at timestamp with time zone,
  time_spent_seconds integer,
  status text NOT NULL DEFAULT 'in_progress'::text CHECK (status = ANY (ARRAY['in_progress'::text, 'submitted'::text, 'timeout'::text, 'abandoned'::text])),
  proctoring_data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  academic_year text,
  exam_type text DEFAULT 'Entrance Examination'::text,
  score integer,
  total_questions integer,
  percentage numeric,
  CONSTRAINT exam_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT exam_sessions_aspirant_id_fkey FOREIGN KEY (aspirant_id) REFERENCES public.profiles(id),
  CONSTRAINT exam_sessions_exam_config_id_fkey FOREIGN KEY (exam_config_id) REFERENCES public.entrance_exam_config(id)
);
CREATE TABLE public.exam_answers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  exam_session_id uuid NOT NULL,
  question_id uuid NOT NULL,
  aspirant_id uuid NOT NULL,
  selected_answer text,
  is_correct boolean,
  points_earned numeric DEFAULT 0,
  answered_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT exam_answers_pkey PRIMARY KEY (id),
  CONSTRAINT exam_answers_exam_session_id_fkey FOREIGN KEY (exam_session_id) REFERENCES public.exam_sessions(id),
  CONSTRAINT exam_answers_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.exam_questions(id),
  CONSTRAINT exam_answers_aspirant_id_fkey FOREIGN KEY (aspirant_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.aspirant_application_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  aspirant_id uuid NOT NULL,
  amount numeric NOT NULL DEFAULT 6500,
  currency text NOT NULL DEFAULT 'NGN'::text,
  payment_method text CHECK (payment_method = ANY (ARRAY['paystack'::text, 'bank_transfer'::text, 'cash'::text])),
  paystack_reference text UNIQUE,
  paystack_access_code text,
  provider_transaction_id text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text, 'abandoned'::text, 'refunded'::text])),
  description text,
  paid_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT aspirant_application_payments_pkey PRIMARY KEY (id),
  CONSTRAINT aspirant_application_payments_aspirant_id_fkey FOREIGN KEY (aspirant_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.aspirant_admission_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  aspirant_id uuid NOT NULL,
  amount numeric NOT NULL DEFAULT 30000,
  currency text NOT NULL DEFAULT 'NGN'::text,
  payment_method text CHECK (payment_method = ANY (ARRAY['paystack'::text, 'bank_transfer'::text, 'cash'::text])),
  paystack_reference text UNIQUE,
  paystack_access_code text,
  provider_transaction_id text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text, 'abandoned'::text, 'refunded'::text])),
  description text,
  paid_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT aspirant_admission_payments_pkey PRIMARY KEY (id),
  CONSTRAINT aspirant_admission_payments_aspirant_id_fkey FOREIGN KEY (aspirant_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.aspirant_payment_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_id uuid,
  payment_type text NOT NULL CHECK (payment_type = ANY (ARRAY['application'::text, 'admission'::text])),
  event_type text NOT NULL,
  provider text DEFAULT 'paystack'::text,
  provider_reference text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  signature text,
  processed boolean NOT NULL DEFAULT false,
  processed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT aspirant_payment_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.exam_violations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  violation_type text NOT NULL CHECK (violation_type = ANY (ARRAY['tab_switch'::text, 'fullscreen_exit'::text, 'visibility_change'::text, 'copy_paste_attempt'::text, 'devtools_open'::text, 'devtools_detected'::text, 'devtools_already_open'::text, 'element_inspection'::text, 'window_resize'::text, 'right_click'::text, 'multiple_persons'::text, 'no_face_detected'::text, 'suspicious_activity'::text, 'other'::text])),
  severity text NOT NULL DEFAULT 'medium'::text CHECK (severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  details text,
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  screenshot_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT exam_violations_pkey PRIMARY KEY (id),
  CONSTRAINT exam_violations_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.exam_sessions(id)
);
CREATE TABLE public.exam_recordings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  recording_url text,
  recording_duration_seconds integer,
  file_size_bytes bigint,
  storage_provider text NOT NULL DEFAULT 'cloudinary'::text,
  status text NOT NULL DEFAULT 'processing'::text CHECK (status = ANY (ARRAY['processing'::text, 'available'::text, 'expired'::text, 'deleted'::text])),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '30 days'::interval),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT exam_recordings_pkey PRIMARY KEY (id),
  CONSTRAINT exam_recordings_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.exam_sessions(id)
);
CREATE TABLE public.exam_proctoring_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  exam_type text NOT NULL DEFAULT 'Entrance Examination'::text,
  max_violations integer NOT NULL DEFAULT 5,
  auto_submit_on_max_violations boolean NOT NULL DEFAULT true,
  record_screen boolean NOT NULL DEFAULT true,
  require_webcam boolean NOT NULL DEFAULT true,
  require_microphone boolean NOT NULL DEFAULT false,
  require_fullscreen boolean NOT NULL DEFAULT true,
  block_copy_paste boolean NOT NULL DEFAULT true,
  block_right_click boolean NOT NULL DEFAULT true,
  block_devtools boolean NOT NULL DEFAULT true,
  detect_tab_switch boolean NOT NULL DEFAULT true,
  detect_visibility_change boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT exam_proctoring_config_pkey PRIMARY KEY (id)
);