-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  first_name text,
  last_name text,
  middle_name text,
  phone text,
  role text NOT NULL DEFAULT 'student'::text CHECK (role = ANY (ARRAY['student'::text, 'lecturer'::text, 'admin'::text, 'super_admin'::text, 'aspirant'::text])),
  avatar_url text,
  is_active boolean NOT NULL DEFAULT true,
  last_seen_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  profile_photo_bucket text NOT NULL DEFAULT 'profile-photos'::text,
  profile_photo_path text UNIQUE,
  profile_photo_mime_type text,
  profile_photo_uploaded_by uuid,
  profile_photo_uploaded_at timestamp with time zone,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_profile_photo_uploaded_by_fkey FOREIGN KEY (profile_photo_uploaded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.student_profiles (
  profile_id uuid NOT NULL,
  student_number text UNIQUE,
  matric_number text UNIQUE,
  admission_session text,
  admission_date date,
  date_of_birth date,
  gender text CHECK (gender = ANY (ARRAY['male'::text, 'female'::text, 'other'::text, 'prefer_not_to_say'::text])),
  blood_group text,
  genotype text,
  state_of_origin text,
  local_government_area text,
  nationality text DEFAULT 'Nigerian'::text,
  address_line_1 text,
  address_line_2 text,
  city text,
  state text,
  guardian_name text,
  guardian_phone text,
  guardian_email text,
  emergency_contact_name text,
  emergency_contact_phone text,
  current_level text,
  admission_status text DEFAULT 'active'::text CHECK (admission_status = ANY (ARRAY['active'::text, 'suspended'::text, 'graduated'::text, 'withdrawn'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT student_profiles_pkey PRIMARY KEY (profile_id),
  CONSTRAINT student_profiles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.teacher_profiles (
  profile_id uuid NOT NULL,
  employee_number text UNIQUE,
  staff_number text UNIQUE,
  qualification text,
  specialization text,
  department text,
  employment_type text CHECK (employment_type = ANY (ARRAY['full_time'::text, 'part_time'::text, 'adjunct'::text, 'contract'::text])),
  date_joined date,
  office_location text,
  office_hours text,
  can_publish_results boolean NOT NULL DEFAULT false,
  can_enter_scores boolean NOT NULL DEFAULT true,
  employment_status text DEFAULT 'active'::text CHECK (employment_status = ANY (ARRAY['active'::text, 'inactive'::text, 'suspended'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT teacher_profiles_pkey PRIMARY KEY (profile_id),
  CONSTRAINT teacher_profiles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.admin_profiles (
  profile_id uuid NOT NULL,
  staff_id text UNIQUE,
  department text,
  designation text,
  admin_scope text DEFAULT 'operations'::text CHECK (admin_scope = ANY (ARRAY['operations'::text, 'academics'::text, 'finance'::text, 'super'::text])),
  can_manage_users boolean NOT NULL DEFAULT false,
  can_manage_content boolean NOT NULL DEFAULT false,
  can_manage_academics boolean NOT NULL DEFAULT false,
  can_manage_finance boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_profiles_pkey PRIMARY KEY (profile_id),
  CONSTRAINT admin_profiles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.academic_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  starts_on date,
  ends_on date,
  is_current boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT academic_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.academic_terms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  term_name text NOT NULL CHECK (term_name = ANY (ARRAY['First Term'::text, 'Second Term'::text, 'Third Term'::text])),
  starts_on date,
  ends_on date,
  is_current boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT academic_terms_pkey PRIMARY KEY (id),
  CONSTRAINT academic_terms_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.academic_sessions(id)
);
CREATE TABLE public.departments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  code text UNIQUE,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT departments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.programs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  description text NOT NULL,
  overview text,
  entry_requirements text,
  career_prospects text,
  duration_months integer NOT NULL,
  duration_unit text NOT NULL CHECK (duration_unit = ANY (ARRAY['months'::text, 'years'::text])),
  tuition_fee numeric NOT NULL,
  curriculum text,
  level text NOT NULL CHECK (level = ANY (ARRAY['certificate'::text, 'diploma'::text, 'degree'::text])),
  department_id uuid,
  max_students integer,
  admission_open boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT programs_pkey PRIMARY KEY (id),
  CONSTRAINT programs_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.courses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  program_id uuid,
  code text NOT NULL UNIQUE,
  title text NOT NULL,
  description text,
  credit_units integer DEFAULT 1,
  level text,
  semester integer,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT courses_pkey PRIMARY KEY (id),
  CONSTRAINT courses_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id)
);
CREATE TABLE public.course_teacher_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  course_id uuid NOT NULL,
  teacher_id uuid NOT NULL,
  session_id uuid,
  term_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT course_teacher_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT course_teacher_assignments_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT course_teacher_assignments_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teacher_profiles(profile_id),
  CONSTRAINT course_teacher_assignments_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.academic_sessions(id),
  CONSTRAINT course_teacher_assignments_term_id_fkey FOREIGN KEY (term_id) REFERENCES public.academic_terms(id)
);
CREATE TABLE public.enrollments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  program_id uuid NOT NULL,
  session_id uuid,
  enrollment_date timestamp with time zone NOT NULL DEFAULT now(),
  expected_graduation_date date,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'dropped'::text, 'deferred'::text, 'withdrawn'::text])),
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT enrollments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT enrollments_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id),
  CONSTRAINT enrollments_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.academic_sessions(id)
);
CREATE TABLE public.assessments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  enrollment_id uuid NOT NULL,
  student_id uuid NOT NULL,
  course_id uuid,
  teacher_id uuid,
  session_id uuid,
  term_id uuid,
  continuous_assessment numeric DEFAULT 0 CHECK (continuous_assessment >= 0::numeric AND continuous_assessment <= 40::numeric),
  exam_score numeric DEFAULT 0 CHECK (exam_score >= 0::numeric AND exam_score <= 60::numeric),
  total_score numeric DEFAULT (COALESCE(continuous_assessment, (0)::numeric) + COALESCE(exam_score, (0)::numeric)),
  grade text CHECK (grade = ANY (ARRAY['A'::text, 'B'::text, 'C'::text, 'D'::text, 'E'::text, 'F'::text])),
  score_status text NOT NULL DEFAULT 'draft'::text CHECK (score_status = ANY (ARRAY['draft'::text, 'submitted'::text, 'approved'::text, 'published'::text])),
  score_entered_at timestamp with time zone,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT assessments_pkey PRIMARY KEY (id),
  CONSTRAINT assessments_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(id),
  CONSTRAINT assessments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT assessments_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT assessments_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teacher_profiles(profile_id),
  CONSTRAINT assessments_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.academic_sessions(id),
  CONSTRAINT assessments_term_id_fkey FOREIGN KEY (term_id) REFERENCES public.academic_terms(id),
  CONSTRAINT assessments_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.admin_profiles(profile_id)
);
CREATE TABLE public.results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  enrollment_id uuid NOT NULL,
  assessment_id uuid,
  course_name text NOT NULL,
  score numeric CHECK (score >= 0::numeric AND score <= 100::numeric),
  grade text CHECK (grade = ANY (ARRAY['A'::text, 'B'::text, 'C'::text, 'D'::text, 'E'::text, 'F'::text])),
  semester integer,
  academic_year text,
  published boolean NOT NULL DEFAULT false,
  published_at timestamp with time zone,
  published_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT results_pkey PRIMARY KEY (id),
  CONSTRAINT results_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT results_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(id),
  CONSTRAINT results_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id),
  CONSTRAINT results_published_by_fkey FOREIGN KEY (published_by) REFERENCES public.admin_profiles(profile_id)
);
CREATE TABLE public.result_publications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  enrollment_id uuid NOT NULL,
  session_id uuid,
  term_id uuid,
  published_by uuid,
  publication_status text NOT NULL DEFAULT 'published'::text CHECK (publication_status = ANY (ARRAY['published'::text, 'unpublished'::text])),
  published_at timestamp with time zone NOT NULL DEFAULT now(),
  notes text,
  CONSTRAINT result_publications_pkey PRIMARY KEY (id),
  CONSTRAINT result_publications_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(id),
  CONSTRAINT result_publications_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.academic_sessions(id),
  CONSTRAINT result_publications_term_id_fkey FOREIGN KEY (term_id) REFERENCES public.academic_terms(id),
  CONSTRAINT result_publications_published_by_fkey FOREIGN KEY (published_by) REFERENCES public.admin_profiles(profile_id)
);
CREATE TABLE public.blog_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  content text NOT NULL,
  excerpt text,
  author_id uuid,
  featured_image_url text,
  tags ARRAY DEFAULT '{}'::text[],
  seo_title text,
  seo_description text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'review'::text, 'published'::text, 'archived'::text])),
  published_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT blog_posts_pkey PRIMARY KEY (id),
  CONSTRAINT blog_posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text NOT NULL,
  event_date timestamp with time zone NOT NULL,
  event_end_date timestamp with time zone,
  location text,
  organizer_id uuid,
  featured_image_url text,
  registration_link text,
  is_published boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_organizer_id_fkey FOREIGN KEY (organizer_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.notices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  content text NOT NULL,
  audience text NOT NULL DEFAULT 'all'::text CHECK (audience = ANY (ARRAY['all'::text, 'students'::text, 'teachers'::text, 'admins'::text])),
  created_by uuid,
  is_published boolean NOT NULL DEFAULT false,
  published_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notices_pkey PRIMARY KEY (id),
  CONSTRAINT notices_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.announcements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  content text NOT NULL,
  created_by uuid,
  is_published boolean NOT NULL DEFAULT false,
  published_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT announcements_pkey PRIMARY KEY (id),
  CONSTRAINT announcements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.contact_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  email text NOT NULL,
  subject text NOT NULL,
  message text NOT NULL,
  status text NOT NULL DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'in_progress'::text, 'resolved'::text, 'archived'::text])),
  handled_by uuid,
  handled_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT contact_messages_pkey PRIMARY KEY (id),
  CONSTRAINT contact_messages_handled_by_fkey FOREIGN KEY (handled_by) REFERENCES public.admin_profiles(profile_id)
);
CREATE TABLE public.fees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  program_id uuid NOT NULL,
  fee_type text NOT NULL CHECK (fee_type = ANY (ARRAY['tuition'::text, 'registration'::text, 'exam'::text, 'library'::text, 'other'::text])),
  amount numeric NOT NULL,
  description text,
  due_in_days integer,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fees_pkey PRIMARY KEY (id),
  CONSTRAINT fees_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  enrollment_id uuid,
  session_id uuid,
  term_id uuid,
  invoice_number text UNIQUE,
  description text,
  amount_due numeric NOT NULL,
  amount_paid numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'NGN'::text,
  due_date date,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'partially_paid'::text, 'paid'::text, 'failed'::text, 'cancelled'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.academic_sessions(id),
  CONSTRAINT invoices_term_id_fkey FOREIGN KEY (term_id) REFERENCES public.academic_terms(id),
  CONSTRAINT invoices_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT invoices_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  enrollment_id uuid,
  invoice_id uuid,
  amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'NGN'::text,
  payment_method text CHECK (payment_method = ANY (ARRAY['paystack'::text, 'bank_transfer'::text, 'cash'::text])),
  paystack_reference text UNIQUE,
  paystack_access_code text,
  provider_transaction_id text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text, 'abandoned'::text, 'refunded'::text])),
  description text,
  paid_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT payments_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(id),
  CONSTRAINT payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.payment_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_id uuid,
  invoice_id uuid,
  event_type text NOT NULL,
  provider text DEFAULT 'paystack'::text,
  provider_reference text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  signature text,
  processed boolean NOT NULL DEFAULT false,
  processed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_events_pkey PRIMARY KEY (id),
  CONSTRAINT payment_events_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id),
  CONSTRAINT payment_events_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.student_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  notification_type text NOT NULL DEFAULT 'general'::text,
  category text,
  deep_link text,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  sent_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT student_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT student_notifications_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.student_profiles(profile_id),
  CONSTRAINT student_notifications_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.teacher_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  notification_type text NOT NULL DEFAULT 'general'::text,
  category text,
  deep_link text,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  sent_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT teacher_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT teacher_notifications_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teacher_profiles(profile_id),
  CONSTRAINT teacher_notifications_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.admin_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  notification_type text NOT NULL DEFAULT 'general'::text,
  category text,
  deep_link text,
  priority text NOT NULL DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'critical'::text])),
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  sent_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT admin_notifications_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.admin_profiles(profile_id),
  CONSTRAINT admin_notifications_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.school_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  value text,
  value_json jsonb,
  is_public boolean NOT NULL DEFAULT false,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT school_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_id uuid,
  actor_role text,
  action text NOT NULL,
  entity_name text NOT NULL,
  entity_id uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.aspirant_profiles (
  profile_id uuid NOT NULL,
  admission_number text UNIQUE,
  jamb_reg_no text NOT NULL UNIQUE,
  preferred_program_id uuid,
  application_type text NOT NULL DEFAULT 'Fresh admission'::text CHECK (application_type = ANY (ARRAY['Fresh admission'::text, 'Transfer candidate'::text, 'Returning applicant'::text, 'Special consideration'::text])),
  application_status text NOT NULL DEFAULT 'draft'::text CHECK (application_status = ANY (ARRAY['draft'::text, 'incomplete'::text, 'submitted'::text, 'under_review'::text, 'correction_required'::text, 'approved'::text, 'rejected'::text])),
  current_stage text NOT NULL DEFAULT 'signup'::text CHECK (current_stage = ANY (ARRAY['signup'::text, 'profile'::text, 'course_selection'::text, 'review'::text, 'submitted'::text, 'admitted'::text])),
  profile_completion integer NOT NULL DEFAULT 0 CHECK (profile_completion >= 0 AND profile_completion <= 100),
  admission_session text,
  submission_notes text,
  submitted_at timestamp with time zone,
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  review_feedback text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT aspirant_profiles_pkey PRIMARY KEY (profile_id),
  CONSTRAINT aspirant_profiles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT aspirant_profiles_preferred_program_id_fkey FOREIGN KEY (preferred_program_id) REFERENCES public.programs(id),
  CONSTRAINT aspirant_profiles_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.admin_profiles(profile_id)
);
CREATE TABLE public.admission_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL,
  uploaded_by uuid NOT NULL,
  document_type text NOT NULL CHECK (document_type = ANY (ARRAY['passport_photo'::text, 'signature'::text, 'birth_certificate'::text, 'age_declaration'::text, 'primary_certificate'::text, 'secondary_certificate'::text, 'indigene_certificate'::text, 'nin_slip'::text, 'jamb_result'::text, 'jamb_registration_form'::text, 'other'::text])),
  storage_bucket text NOT NULL DEFAULT 'admission-documents'::text,
  storage_path text NOT NULL UNIQUE,
  file_name text NOT NULL,
  mime_type text,
  file_size bigint,
  verification_status text NOT NULL DEFAULT 'pending'::text CHECK (verification_status = ANY (ARRAY['pending'::text, 'verified'::text, 'rejected'::text, 'needs_correction'::text])),
  verification_note text,
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  verified_by uuid,
  verified_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admission_documents_pkey PRIMARY KEY (id),
  CONSTRAINT admission_documents_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.aspirant_profiles(profile_id),
  CONSTRAINT admission_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id),
  CONSTRAINT admission_documents_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.admin_profiles(profile_id)
);
CREATE TABLE public.aspirant_profile_photos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL,
  uploaded_by uuid NOT NULL,
  storage_bucket text NOT NULL DEFAULT 'profile-photos'::text,
  storage_path text NOT NULL UNIQUE,
  file_name text NOT NULL,
  mime_type text,
  file_size bigint,
  is_primary boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT aspirant_profile_photos_pkey PRIMARY KEY (id),
  CONSTRAINT aspirant_profile_photos_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.aspirant_profiles(profile_id),
  CONSTRAINT aspirant_profile_photos_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.admission_status_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL,
  previous_status text,
  new_status text NOT NULL,
  note text,
  changed_by uuid,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admission_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT admission_status_history_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.aspirant_profiles(profile_id),
  CONSTRAINT admission_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.profiles(id)
);